# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gg3nDEnrleWEQpHQqBBeo55JipeorTpR
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
import json
from sklearn.preprocessing import LabelEncoder

# ── Page Configuration ───────────────────────────────────────────
st.set_page_config(
    page_title="Diabetes Risk Predictor",
    page_icon="🩺",
    layout="centered"
)

# ── Load saved model and transformers ───────────────────────────
@st.cache_resource
def load_artifacts():
    """Loads the trained model, scaler, selector, and feature names."""
    model    = joblib.load('diabetes_model.pkl')
    scaler   = joblib.load('scaler.pkl')
    selector = joblib.load('selector.pkl')
    with open('selected_features.json', 'r') as f:
        selected_features = json.load(f)
    return model, scaler, selector, selected_features

model, scaler, selector, selected_features = load_artifacts()

# ── Helper Functions ─────────────────────────────────────────────
def get_age_group(age):
    """Converts raw age into a clinical risk group label."""
    if age < 30:   return 'Young'
    elif age < 45: return 'Middle Aged'
    elif age < 60: return 'Pre-Senior'
    else:          return 'Senior'

def get_bmi_category(bmi):
    """Converts raw BMI into a clinical weight category label."""
    if bmi < 18.5: return 'Underweight'
    elif bmi < 25: return 'Normal'
    elif bmi < 30: return 'Overweight'
    else:          return 'Obese'

def get_glucose_risk(glucose):
    """
    Classifies blood glucose into clinical risk categories
    based on standard medical thresholds.

    Parameters:
        glucose : float blood glucose reading
    Returns:
        string risk label
    """
    if glucose < 100:   return 'Normal'
    elif glucose < 126: return 'Pre-Diabetic'
    else:               return 'Diabetic Range'

def get_risk_score(hypertension, heart_disease, bmi, hba1c):
    """
    Combines 4 binary risk factors into a single composite score.

    Parameters:
        hypertension  : 0 or 1
        heart_disease : 0 or 1
        bmi           : float
        hba1c         : float
    Returns:
        integer score from 0 to 4
    """
    score = 0
    if hypertension == 1:  score += 1
    if heart_disease == 1: score += 1
    if bmi >= 30:          score += 1
    if hba1c >= 6.5:       score += 1
    return score

def encode_features(raw_df):
    """
    Applies label encoding to categorical columns.
    Matches the same encoding logic used during training.

    Parameters:
        raw_df : DataFrame with one row of raw user input
    Returns:
        Encoded DataFrame
    """
    le = LabelEncoder()
    df = raw_df.copy()
    cat_cols = df.select_dtypes(include='object').columns
    for col in cat_cols:
        df[col] = le.fit_transform(df[col].astype(str))
    return df

def preprocess_input(gender, age, hypertension, heart_disease,
                     smoking_history, bmi, hba1c, blood_glucose):
    """
    Full preprocessing pipeline: build → engineer features →
    encode → scale → select features.

    Parameters:
        All raw user inputs from the Streamlit form
    Returns:
        Preprocessed numpy array ready for prediction
    """
    # ── Build base row matching training columns ─────────────────
    raw = {
        'gender':              gender,
        'age':                 int(age),
        'hypertension':        hypertension,
        'heart_disease':       heart_disease,
        'smoking_history':     smoking_history,
        'bmi':                 float(bmi),
        'HbA1c_level':         float(hba1c),
        'blood_glucose_level': float(blood_glucose),
    }
    df = pd.DataFrame([raw])

    # ── Add engineered features ──────────────────────────────────
    df['age_group']    = df['age'].apply(get_age_group)
    df['bmi_category'] = df['bmi'].apply(get_bmi_category)
    df['glucose_risk'] = df['blood_glucose_level'].apply(get_glucose_risk)
    df['risk_score']   = get_risk_score(
        hypertension, heart_disease, bmi, hba1c
    )

    # ── Encode categorical columns ───────────────────────────────
    df_encoded = encode_features(df)

    # ── Scale using saved scaler ─────────────────────────────────
    df_scaled = pd.DataFrame(
        scaler.transform(df_encoded),
        columns=df_encoded.columns
    )

    # ── Select features using saved selector ─────────────────────
    df_selected = df_scaled[selected_features]

    return df_selected.values

# ── UI Layout ────────────────────────────────────────────────────
st.title("🩺 Diabetes Risk Predictor")
st.markdown("Enter patient information below to assess diabetes risk.")
st.divider()

# ── Input Form ───────────────────────────────────────────────────
col1, col2 = st.columns(2)

with col1:
    gender          = st.selectbox("Gender", ["Female", "Male"])
    age             = st.slider("Age", min_value=1, max_value=80, value=40)
    hypertension    = st.selectbox("Hypertension",
                                    [0, 1],
                                    format_func=lambda x: "Yes" if x else "No")
    heart_disease   = st.selectbox("Heart Disease",
                                    [0, 1],
                                    format_func=lambda x: "Yes" if x else "No")

with col2:
    smoking_history = st.selectbox("Smoking History",
                                    ["never", "former", "current",
                                     "ever", "not current"])
    bmi             = st.slider("BMI", min_value=10.0,
                                 max_value=60.0, value=25.0, step=0.1)
    hba1c           = st.slider("HbA1c Level", min_value=3.5,
                                 max_value=9.0, value=5.5, step=0.1)
    blood_glucose   = st.slider("Blood Glucose Level",
                                 min_value=80, max_value=300, value=100)

st.divider()

# ── Predict Button ───────────────────────────────────────────────
if st.button("🔍 Predict Diabetes Risk", use_container_width=True):

    processed   = preprocess_input(
        gender, age, hypertension, heart_disease,
        smoking_history, bmi, hba1c, blood_glucose
    )
    prediction  = model.predict(processed)[0]
    probability = model.predict_proba(processed)[0][1]

    # ── Display Result ───────────────────────────────────────────
    st.subheader("Prediction Result")

    if prediction == 1:
        st.error("⚠️ High Diabetes Risk Detected")
        st.metric("Diabetes Probability", f"{probability*100:.1f}%")
        st.warning("This patient shows elevated diabetes risk. "
                   "Please consult a medical professional.")
    else:
        st.success("✅ Low Diabetes Risk")
        st.metric("Diabetes Probability", f"{probability*100:.1f}%")
        st.info("No immediate diabetes risk detected "
                "based on the provided data.")

    # ── Risk Factor Summary ──────────────────────────────────────
    st.subheader("Patient Risk Summary")

    risk_factors = []
    if hba1c >= 6.5:
        risk_factors.append("🔴 HbA1c in diabetic range (≥ 6.5%)")
    if blood_glucose >= 126:
        risk_factors.append("🔴 Blood glucose in diabetic range (≥ 126)")
    if hypertension == 1:
        risk_factors.append("🔴 Has hypertension")
    if heart_disease == 1:
        risk_factors.append("🔴 Has heart disease")
    if bmi >= 30:
        risk_factors.append("🟡 Obese BMI (≥ 30)")
    if age >= 45:
        risk_factors.append("🟡 Age 45 or above")
    if smoking_history == "current":
        risk_factors.append("🟡 Current smoker")
    if hba1c >= 5.7:
        risk_factors.append("🟡 HbA1c in pre-diabetic range (≥ 5.7%)")
    if blood_glucose >= 100:
        risk_factors.append("🟡 Blood glucose in pre-diabetic range (≥ 100)")

    if risk_factors:
        for factor in risk_factors:
            st.write(factor)
    else:
        st.write("✅ No major risk factors detected.")

# ── Footer ───────────────────────────────────────────────────────
st.divider()
st.caption("Built with Streamlit · Diabetes Prediction ML Project · "
           "For educational purposes only")